### ISSUE TITLE
`no implicit conversion of nil into String` error when running soloist

### ISSUE THREAD

**Issue by smartb-pair** [pivotal-sprout/sprout-homebrew#23]
We're calling this cookbook from sprout wrap on El Capitan pairing stations, and getting the following error - we are continuing to investigate as we have time but we don't yet know what's going on. Relevant error output:
```
Recipe: sprout-homebrew::cask
  * directory[/usr/local/Library/Taps] action create[2016-01-19T11:15:26+01:00] INFO: Processing directory[/usr/local/Library/Taps] action create (sprout-homebrew::cask line 3)
 (up to date)
  * execute[tap cask] action run[2016-01-19T11:15:26+01:00] INFO: Processing execute[tap cask] action run (sprout-homebrew::cask line 8)
Warning: Tap caskroom/cask already tapped.
[2016-01-19T11:15:27+01:00] INFO: execute[tap cask] ran successfully

    - execute brew tap "caskroom/homebrew-cask"
  * homebrew_package[caskroom/cask/brew-cask] action install[2016-01-19T11:15:27+01:00] INFO: Processing homebrew_package[caskroom/cask/brew-cask] action install (sprout-homebrew::cask line 13)


    ================================================================================
    Error executing action `install` on resource 'homebrew_package[caskroom/cask/brew-cask]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of nil into String

    Cookbook Trace:
    ---------------
    /Users/smartb/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:94:in `get_version_from_formula'
    /Users/smartb/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:74:in `current_installed_version'
    /Users/smartb/sprout-wrap/cookbooks/homebrew/libraries/homebrew_package.rb:44:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /Users/smartb/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb

     13: package 'caskroom/cask/brew-cask'
     14:

    Compiled Resource:
    ------------------
    # Declared in /Users/smartb/sprout-wrap/cookbooks/sprout-homebrew/recipes/cask.rb:13:in `from_file'

    homebrew_package("caskroom/cask/brew-cask") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "caskroom/cask/brew-cask"
      declared_type :package
      cookbook_name :"sprout-homebrew"
      recipe_name "cask"
    end

[2016-01-19T11:15:27+01:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2016-01-19T11:15:27+01:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-19T11:15:27+01:00] ERROR: Exception handlers complete
Chef Client failed. 12 resources updated in 36.638406 seconds
[2016-01-19T11:15:27+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-01-19T11:15:27+01:00] ERROR: homebrew_package[caskroom/cask/brew-cask] (sprout-homebrew::cask line 13) had an error: TypeError: no implicit conversion of nil into String
[2016-01-19T11:15:27+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

/cc @bixu @arochaf

**Comment by timjacobi** [comment]
#22 Should fix this

**Comment by nfuller52** [comment]
Perhaps I did it incorrectly, but I ran sprout-wrap with the proposed solution in #22, which got be beyond the brew-cask items, but I ran into the same error "no implicit conversion of nil into String
" when installing formulas

**Comment by pivotal-rebecca** [comment]
We are also having this problem.  We tried this also, and are getting the `no implicit conversion of nil into String` now at `homebrew_package[ctags-exuberant]` install.

**Comment by hiremaga** [comment]
Looks related to https://github.com/chef-cookbooks/homebrew/issues/87

I don't think #22 is sufficient to resolve this since I've seen similar errors installing other homebrew packages. Continuing to investigate...

**Comment by hiremaga** [comment]
Looks like version 2.0.4 of the homebrew cookbook fixes this, please run `librarian-chef update homebrew` in your team's sprout-wrap to get this.

**Comment by hiremaga** [comment]
See https://github.com/chef-cookbooks/homebrew/pull/88 for more context.
